alias ll='ls -alFh'
alias kk='ls -alFh'
alias gst='git status'
alias gl='git log'
alias cpwd='pwd|pbcopy'
alias grepflict='grep -lr "<<<<<<" .'
alias grep='grep --color=auto'
alias sc='screen'
alias ifcfg='ifconfig | grep netmask'
alias gti='git'
alias gut='git'
alias gst='git st'
alias j='z'
alias gitpush='git push origin $(git symbolic-ref --short HEAD)'
alias gitprb='git pull --rebase origin $(git symbolic-ref --short HEAD)'